- id: '1693774367487'
  alias: Oppvåkning
  description: ''
  triggers:
  - at: 05:30:00
    enabled: true
    trigger: time
  conditions:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    enabled: true
  actions:
  - data:
      brightness_pct: 25
    target:
      entity_id: light.soverom_lys
    action: light.turn_on
  - delay:
      hours: 0
      minutes: 10
      seconds: 0
      milliseconds: 0
  - data:
      brightness_pct: 50
    target:
      entity_id: light.soverom_lys
    action: light.turn_on
  - delay:
      hours: 0
      minutes: 10
      seconds: 0
      milliseconds: 0
  - data:
      brightness_pct: 75
    target:
      entity_id: light.soverom_lys
    action: light.turn_on
  - delay:
      hours: 0
      minutes: 10
      seconds: 0
      milliseconds: 0
  - data:
      brightness_pct: 100
    target:
      entity_id: light.soverom_lys
    action: light.turn_on
  - data: {}
    target:
      entity_id:
      - scene.normal_entre_lys
      - scene.normal_gang_lys
    action: scene.turn_on
  - delay:
      hours: 2
      minutes: 0
      seconds: 0
      milliseconds: 0
  - data: {}
    target:
      entity_id:
      - light.soverom_lys
      - light.taklampe_entre
      - light.taklampe_gang
    action: light.turn_off
  mode: single
- id: '1693889737574'
  alias: Drar hjemmefra
  description: ''
  trigger:
  - platform: zone
    entity_id: person.anders
    zone: zone.home
    event: leave
  condition: []
  action:
  - data: {}
    target:
      entity_id: light.alle_lys
    action: light.turn_off
  - data: {}
    target:
      entity_id:
      - media_player.melina
      - media_player.stue
      - media_player.melina_2
    action: media_player.turn_off
  mode: single
- id: '1695112118552'
  alias: Nattlys
  description: ''
  triggers:
  - device_id: d3c4ab4b39d5788d4a79ec1bdeb2f2ac
    domain: zha
    type: remote_button_short_press
    subtype: turn_on
    trigger: device
  conditions: []
  actions:
  - if:
    - condition: state
      entity_id: binary_sensor.nattlys
      state: 'off'
    then:
    - target:
        entity_id: scene.nattlys
      metadata: {}
      action: scene.turn_on
      data: {}
    else:
    - data: {}
      target:
        entity_id: light.alle_lys
      action: light.turn_off
  mode: single
- id: '1695139713739'
  alias: Alle lys
  description: ''
  trigger: []
  condition: []
  action:
  - if:
    - condition: state
      entity_id: light.alle_lys
      state: 'off'
    then:
    - service: scene.turn_on
      target:
        entity_id: scene.normal_entre_lys
      metadata: {}
    - service: scene.turn_on
      target:
        entity_id: scene.normal_gang_lys
      metadata: {}
    - service: scene.turn_on
      target:
        entity_id: scene.normal_soverom_lys
      metadata: {}
    - service: scene.turn_on
      target:
        entity_id: scene.normal_stue_lys
      metadata: {}
    else:
    - service: light.turn_off
      data: {}
      target:
        entity_id: light.alle_lys
  mode: single
- id: '1695326503541'
  alias: Slå på filmlys
  description: ''
  trigger:
  - platform: state
    entity_id:
    - media_player.melina
    to: playing
  condition:
  - condition: state
    entity_id: binary_sensor.stuelys
    state: 'on'
  - condition: not
    conditions:
    - condition: state
      entity_id: media_player.melina_2
      attribute: app_name
      state: com.spotify.tv.android
  action:
  - data:
      transition: 2
    target:
      entity_id: scene.filmlys
    action: scene.turn_on
  mode: single
- id: '1695326594430'
  alias: Slå av filmlys
  description: ''
  trigger:
  - platform: state
    entity_id:
    - media_player.melina
    from: playing
  condition:
  - condition: state
    entity_id: binary_sensor.filmlys
    state: 'on'
  action:
  - data:
      transition: 2
    target:
      entity_id: scene.normal_stue_lys
    action: scene.turn_on
  mode: single
- id: '1695395763989'
  alias: Åpen kjøleskapsdør
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.kjoleskapsdorsensor_apning
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: script.kjoleskapsdoralarm
    data: {}
  mode: single
- id: '1695397968381'
  alias: Åpen fryseskapsdør
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.fryseskapsdorsensor_apning
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: script.fryseskapsdoralarm
    data: {}
  mode: single
- id: '1699814369938'
  alias: Manuell oppvåkning
  description: ''
  triggers:
  - at: 07:30:00
    enabled: true
    trigger: time
  conditions: []
  actions:
  - data:
      transition: 300
      brightness_pct: 25
    target:
      entity_id: light.soverom_lys
    action: light.turn_on
  - delay:
      hours: 0
      minutes: 10
      seconds: 0
      milliseconds: 0
  - data:
      transition: 300
      brightness_pct: 50
    target:
      entity_id: light.soverom_lys
    action: light.turn_on
  - delay:
      hours: 0
      minutes: 10
      seconds: 0
      milliseconds: 0
  - data:
      transition: 300
      brightness_pct: 75
    target:
      entity_id: light.soverom_lys
    action: light.turn_on
  - delay:
      hours: 0
      minutes: 10
      seconds: 0
      milliseconds: 0
  - data:
      transition: 300
      brightness_pct: 100
    target:
      entity_id: light.soverom_lys
    action: light.turn_on
  - data: {}
    target:
      entity_id:
      - scene.normal_entre_lys
      - scene.normal_gang_lys
    action: scene.turn_on
  - delay:
      hours: 2
      minutes: 0
      seconds: 0
      milliseconds: 0
  - data: {}
    target:
      entity_id:
      - light.soverom_lys
      - light.taklampe_entre
      - light.taklampe_gang
    action: light.turn_off
  mode: single
- id: '1704641582142'
  alias: Slå på alle lys
  description: ''
  triggers:
  - device_id: db7cc31bffcbed23d9852e5f2f6cdc22
    domain: zha
    type: remote_button_short_press
    subtype: button_1
    trigger: device
  conditions: []
  actions:
  - metadata: {}
    target:
      entity_id: scene.normal_entre_lys
    action: scene.turn_on
    data: {}
  - metadata: {}
    target:
      entity_id: scene.normal_gang_lys
    action: scene.turn_on
    data: {}
  - metadata: {}
    target:
      entity_id: scene.normal_stue_lys
    action: scene.turn_on
    data: {}
  - metadata: {}
    target:
      entity_id: scene.normal_soverom_lys
    action: scene.turn_on
    data: {}
  mode: single
- id: '1704641616888'
  alias: Slå av alle lys
  description: ''
  triggers:
  - device_id: db7cc31bffcbed23d9852e5f2f6cdc22
    domain: zha
    type: remote_button_short_press
    subtype: button_2
    trigger: device
  conditions: []
  actions:
  - metadata: {}
    data: {}
    target:
      entity_id: light.alle_lys
    action: light.turn_off
  mode: single
- id: '1705666507793'
  alias: Slå på soveromslys
  description: ''
  triggers:
  - device_id: d3c4ab4b39d5788d4a79ec1bdeb2f2ac
    domain: zha
    type: remote_button_long_press
    subtype: dim_up
    trigger: device
  conditions: []
  actions:
  - if:
    - condition: state
      state: 'off'
      entity_id: light.taklampe_soverom_lys
    then:
    - target:
        entity_id: scene.normal_soverom_lys
      metadata: {}
      action: scene.turn_on
      data: {}
    else:
    - data: {}
      target:
        entity_id: light.soverom_lys
      action: light.turn_off
  mode: single
- id: '1737455495542'
  alias: 3D print ferdig
  description: ''
  triggers:
  - device_id: c76309f5f45801bb917a20ba42c55386
    domain: bambu_lab
    type: event_print_finished
    trigger: device
  conditions: []
  actions:
  - type: turn_off
    device_id: c76309f5f45801bb917a20ba42c55386
    entity_id: 352ef6f7c6e066e99dab82386d519b0b
    domain: light
  - action: notify.mobile_app_anders_sin_iphone
    metadata: {}
    data:
      message: '3D printen er ferdig: {{ states(''sensor.prints_charming_task_name'')
        }}'
      title: Prints Charming
  mode: single
